# Place at the very top of admin/config.yml
backend:
  name: github
  repo: hdc-ewb-cwru/hdc-ewb-cwru.github.io
  branch: main # or vmc

# Media configuration
media_folder: "assets/images"
public_folder: "/assets/images"

# Collections
collections:
  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Project Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }