backend:
  name: github
  repo: hdc-ewb-cwru/hdc-ewb-cwru.github.io
  branch: main
  base_url: https://decap-oauth-backend.vercel.app # Free community OAuth proxy
  auth_endpoint: /api/auth

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Project Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }